# Generated by Django 4.2.27 on 2025-12-22 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='registration_number',
            field=models.CharField(db_index=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Registration number must be 6-20 characters, alphanumeric uppercase only', regex='^[A-Z0-9]{6,20}$')]),
        ),
        migrations.AddConstraint(
            model_name='companyprofile',
            constraint=models.UniqueConstraint(fields=('registration_number',), name='unique_company_registration'),
        ),
    ]
