# Generated by Django 4.2.27 on 2025-12-24 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_profile_photo'),
    ]

    operations = [
    ]
