# Generated by Django 4.2.27 on 2025-12-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20251224_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasteproduct',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='waste_photos/'),
        ),
    ]
