# Generated by Django 4.2.27 on 2025-12-24 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pricing_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasteproduct',
            name='farmer_price_per_ton',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price set by farmer (can bargain from admin price)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='wasteproduct',
            name='admin_price_per_ton',
            field=models.DecimalField(decimal_places=2, help_text='Price set by admin for farmers', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
