# Generated by Django 4.2.27 on 2025-12-24 07:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_wasteproduct_farmer_price_per_ton_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceBargain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_proposed_price', models.DecimalField(decimal_places=2, help_text='Price proposed by farmer', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('admin_counter_price', models.DecimalField(blank=True, decimal_places=2, help_text='Counter price by admin', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('farmer_message', models.TextField(help_text="Farmer's bargaining message")),
                ('admin_message', models.TextField(blank=True, help_text="Admin's response message")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('waste_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bargains', to='core.wasteproduct')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
