# Generated by Django 4.2.27 on 2025-12-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pricebargain'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_notes',
            field=models.TextField(blank=True, help_text="Admin's notes"),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_admin', 'Pending Admin Approval'), ('approved_by_admin', 'Approved by Admin'), ('pending_farmer', 'Pending Farmer Response'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending_admin', max_length=20),
        ),
    ]
